# Create here the Drupal site you would like
version: '2'
services:
  drupal:
    # Choose your URL and hostname for this Docker Container
    # NEEDS to end with '.docker.amazee.io' !
    # DO NOT remove the '&hostname'
    hostname: &hostname imatra.com.docker.amazee.io

    environment:

      WEBROOT: public

      # If you would like to use blackfire.io, uncomment and add your server credentials:
      #BLACKFIRE_SERVER_ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      #BLACKFIRE_SERVER_TOKEN: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

      # If you want to use stage_file_proxy, uncomment following line and add the production url of your website:
      #AMAZEEIO_PRODUCTION_URL: 'http://example.com'

      # APC Support is by default enabled, but in some cases it can make issues, change to 0 to disable:
      APC: 1

      VIRTUAL_HOST: *hostname
    image: amazeeio/drupal:php56-basic
    volumes:
      - .:/var/www/drupal/public_html
    volumes_from:
      - container:amazeeio-ssh-agent
    container_name: *hostname
    network_mode: bridge
    ports:
      - "3306"
    links:
      - solr
  solr:
    image: amazeeio/solr:5
    network_mode: bridge
    #volumes:
      # per default our solr image is shipped with a default config (see docs), which is good
      # for Drupal 7 and 8 and search_api module. If by any reason you need to change the solr config
      # put the config files in a folder 'amazeeio/solr-conf' and uncomment this line:
      #- ./amazeeio/solr-conf:/solr-conf